name: CI

on:
  push:
    branches: [ main ]
    tags-ignore: [ '**' ]
  pull_request:

permissions:
  contents: read

jobs:
  mysql57:
    uses: 9506hqwy/actions/.github/workflows/redmine-ci-mysql57.yml@main

  mysql80:
    uses: 9506hqwy/actions/.github/workflows/redmine-ci-mysql80.yml@main

  postgres:
    uses: 9506hqwy/actions/.github/workflows/redmine-ci-postgres.yml@main

  sqlite3:
    uses: 9506hqwy/actions/.github/workflows/redmine-ci-sqlite3.yml@main
